config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  post 'home/get_form_data', to: 'home#get_form_data', as: :get_form_data
  get 'home/list_of_contact', to: 'home#list_of_contact', as: :list_of_contact
  post 'home/get_language', to: 'home#get_language'
  get '/store_language', to: 'home#store_language'
  root 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/models/user_language.rb
class UserLanguage < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

	around_action :switch_locale
	 
	def switch_locale(&action)
	  locale = extract_locale_from_tld || I18n.default_locale
	  I18n.with_locale(locale, &action)
	end
	 
	def extract_locale_from_tld
	  @language = UserLanguage.find_by ip_address: remote_ip()
	  parsed_locale = @language.present? ? @language.language : 'en' 
	  I18n.available_locales.map(&:to_s).include?(parsed_locale) ? parsed_locale : nil
	end

	def remote_ip
      request.remote_ip
 	end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
		@language = UserLanguage.find_by ip_address: remote_ip()
		@contact = Contact.new
	end

	def get_form_data
		contact = Contact.new(contact_params)
		if contact.save
			ContactMailer.with(contact: contact).sent_contact_mail.deliver_now	
      		flash[:notice] = "Details saved and mail sent successfully."
		else
      		flash[:error] = "Details not saved due to some error."
		end
		redirect_to root_path
	end

	def store_language
		lang = params["language"].present? ? params["language"].downcase[0..1] : 'en'
		@language = UserLanguage.find_by ip_address: remote_ip()
		if @language.present?
			@language.update(ip_address: remote_ip(), language: lang)
		else
			UserLanguage.create(ip_address: remote_ip(), language: lang)
		end
		respond_to do |format|
		    format.html  { redirect_to root_path }
		    format.js  { redirect_to root_path }
  		end
	end

	def list_of_contact
		@contacts = Contact.all
	end

	private

	def contact_params
		params.require(:contact).permit(:first_name, :last_name, :email, :mobile, :message)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def bootstrap_class_for(flash_type)
      case flash_type
        when "success"
          "alert-success"
        when "error"
          "alert-danger"
        when "alert"
          "alert-warning"
        when "notice"
          "alert-info"
        else
          flash_type.to_s
        end
    end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
</div>
<div id="dropDownSelect1">
	<% lang = @language.present? && @language.language.eql?('ru') ? 'Russian' : 'English' %>
	<%= select_tag "language_select", options_for_select([ 'Russian', 'English'], lang) %>
</div>
<div class="container-contact100">
	<div class="wrap-contact100">
		<%= form_for @contact, url: get_form_data_path, html: { class: "contact100-form new_contact_form validate-form" } do |f| %>
			<span class="contact100-form-title">
				<%= t 'send_us_message' %>
			</span>

			<label class="label-input100" for="first-name"><%= t 'tell_us_your_name' %> *</label>
			<div class="wrap-input100 rs1-wrap-input100 validate-input" data-validate="Type first name">
                <%= f.text_field :first_name, class: 'input100 required', placeholder: "#{t 'first_name'}", required: true %>
			</div>
			<div class="wrap-input100 rs2-wrap-input100 validate-input" data-validate="Type last name">
                <%= f.text_field :last_name, class: 'input100 required', placeholder: "#{t 'last_name'}", required: true %>
			</div>

			<label class="label-input100" for="email"><%= t 'enter_your_email' %> *</label>
			<div class="wrap-input100 validate-input" data-validate = "Valid email is required: ex@abc.xyz">
                <%= f.email_field :email, class: 'input100 required', placeholder: "#{t 'email_placeholder'}", required: true %>
			</div>

			<label class="label-input100" for="phone"><%= t 'enter_your_number' %></label>
			<div class="wrap-input100">
                <%= f.text_field :mobile, class: 'input100 required', placeholder: "#{t 'mobile_placeholder'}", required: true %>
			</div>

			<label class="label-input100" for="message"><%= t 'enter_message' %> *</label>
			<div class="wrap-input100 validate-input" data-validate = "Message is required">
                <%= f.text_area :message, class: 'input100 required', rows: '4', placeholder: "#{t 'message_placeholder'}", required: true %>
			</div>

			<div class="container-contact100-form-btn">
				<%= f.submit t('send_message'), class: 'contact100-form-btn' %>
			</div>
		<% end %>
		<div class="contact100-more flex-col-c-m" style="background-image: url('<%= asset_path('bg-01.jpg') %>');">
			<div class="flex-w size1 p-b-47">
				<div class="txt1 p-r-25">
					<span class="lnr lnr-map-marker"></span>
				</div>

				<div class="flex-col size2">
					<span class="txt1 p-b-20">
						<%= t 'address' %>
					</span>

					<span class="txt2">
						<%= t 'get_address' %>
					</span>
				</div>
			</div>

			<div class="dis-flex size1 p-b-47">
				<div class="txt1 p-r-25">
					<span class="lnr lnr-phone-handset"></span>
				</div>

				<div class="flex-col size2">
					<span class="txt1 p-b-20">
						<%= t 'lets_talk' %>
					</span>

					<span class="txt3">
						<%= t 'mobile_number' %>
					</span>
				</div>
			</div>

			<div class="dis-flex size1 p-b-47">
				<div class="txt1 p-r-25">
					<span class="lnr lnr-envelope"></span>
				</div>

				<div class="flex-col size2">
					<span class="txt1 p-b-20">
						<%= t 'general_support' %>
					</span>

					<span class="txt3">
						<%= t 'email_id' %>
					</span>
				</div>
			</div>
		</div>
	</div>

app/views/home/list_of_contact.html.erb
<table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">First name</th>
      <th scope="col">Last name</th>
      <th scope="col">Mobile</th>
      <th scope="col">Email</th>
      <th scope="col">Message</th>
    </tr>
  </thead>
  <tbody>
  	<% @contacts.each_with_index do |contact,  index| %>
  		<tr>
			<th scope="col"><%= index + 1 %></th>
			<th scope="col"><%= contact.first_name %></th>
			<th scope="col"><%= contact.last_name %></th>
			<th scope="col"><%= contact.mobile %></th>
			<th scope="col"><%= contact.email %></th>
			<th scope="col"><%= contact.message %></th>
    	</tr>
  	<% end %>
  </tbody>
 </table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ContactForm</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <!-- <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script> -->
    <!-- <script src="http://ajax.aspnetcdn.com/ajax/jquery.validate/1.11.1/jquery.validate.min.js"></script> -->
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% flash.each do |type, message| %>
      <div class="alert <%= bootstrap_class_for(type) %> alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <%= message %>
      </div>
    <% end %>
    <%= yield %>
  </body>
</html>